<!doctype html>

<html lang="en"><head>
    <!-- Required meta tags -->


    <!--<title>About Rustenburg</title>-->

    <?php include ('../includes/inc_page_metadata.php')?>
    <?php include_once ('../config/connection.php') ?>
    <?php include_once ('../functions/functions.php') ?>
</head><body>


<!-- navigation -->
<?php include ('../includes/inc_header.php')?>
<!-- nav part end -->
<?php //include('../includes/inc_pagename.php') ?>
<!-- content-->

 <!--<h2 class="title">Waste Management</h2>-->
 
 <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url('../images/Screen Shot 2017-09-20 at 2.17.03 PM copy_0.png');">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Waste Management</h2>
              <!--<p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>-->
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="http://localhost/Rusty/">Home</a></li>
            <li>Waste Management</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->
 

<div class="container">

		  
          <!-- <h2 class="title">Waste Management</h2>-->
		   
            <p style ="text-align:justify;"><strong>WE ARE COMMITTED TO:</strong> An affordable and fair tariff for different users based on an open and transparent approach to the cost of solid waste services. Ensure regular and accurate accounts, provide adequate facilities accessible to all consumers to pay, query and verify accounts and quick response times to deal with complaints, queries and rectification of accounts should this be necessary. Provide our consumers with the opportunity to give us feedback in respect of the quality of services and the performance of the Municipality. Maintain the existing and further build a sound customer management system focused on good customer relations and customer satisfaction based on the Batho Pele Principles.</p>
			
			<p style ="text-align:justify;"><strong>Recycling:</strong> The Municipality may request residents and businesses to separate recyclable (e.g. paper, plastics, glass and metal) and non-recyclable waste and place recyclables in a different receptacle as provided, e.g. clear bags on specific days at the entrance of your premises for collection. The Municipality may also request these recyclable containers to be dropped off at places as directed including e-waste such as batteries or fluorescent lights. Unless acting according to the Municipality’s waste by-laws, no one may temporary accumulate, sort, store or stockpile recyclable waste on any premises. Only a licensed service provider may collect recyclable waste from premises where it is generated/separated from other waste and transport and dispose of it at a material recovery facility / waste disposal facility designated by the Municipality.</p>
			
			<p style ="text-align:justify;"><strong>Solid Waste Service Levels & Standards:</strong> Corruption is our common enemy. We are committed to prevent and fight against corruption in the Municipality. Help us by reporting corruption to the national anti-corruption hotline at 0800 701 701 We supply: Residential premises with one 240l approved waste container or more if the Municipality so determines or if so requested in writing based on volume and at the prescribed fee. Group developments, schools, churches, old age homes, hospitals and business premises with the number of approved waste containers determined by the Municipality or as requested in writing based on volume and frequency requirements and at the prescribed fee. Bulk containers at clearly demarcated central communal collection points. Suitable litter containers in public areas.</p>
			
			<p style ="text-align:justify;"><strong>We collect:</strong> Domestic waste in high density areas and business waste at least once per week on scheduled dates. Business waste more frequently if the Municipality is of the opinion that the type and/or volume of waste necessitate it or public health demands it or if in writing requested thereto by a business. Bulk containers from communal collection points once per week or within 24 hours after being notified that a container is full.</p>
			   
			 <p style ="text-align:justify;"><strong>We will:</strong> Endeavour to answer customer calls within 5 ringtones. Return your call within 24 hours / one working day. Investigate and respond to any odour complaints within 24 hours or on the following working day. Respond to written correspondence: a first response within 14 days and, if an investigation is needed, resolve the matter within 30 working days. Inform you of revised collection arrangements reasonably in advance. Resume a scheduled refuse collection service that was interrupted, as soon as possible and prioritise addressing backlogs. Clean any spillages made by our collection teams on the same day. Take care to avoid damage to containers or other property and nuisance to other residents or traders.</p>
			 
			 <p style ="text-align:justify;"><strong>Waste containers:</strong> Domestic waste: this is waste generated by people living in houses, flats, old age homes, group developments, schools, churches, sport and recreation centers. Business waste: this is waste generated on premises used for non-residential premises and residential premises where commercial activities take place. These premises are either zoned for commercial activities or received consent use for such activities. Excluded from both domestic and business waste are garden waste, building waste as well as hazardous, special and industrial waste types that have physical, chemical and/or toxic characteristics that requires special handling, e.g. mining liquids, sludge, dead animals, etc. The Municipality may determine if waste items are not suitable for collection because of volume or type. A person who generates domestic or business waste is the owner thereof until collected by the Municipality. If the Municipality is impeded from collecting/handling waste due to the layout of the premises, the Municipality may request the owner/occupier to make changes at own cost to provide proper, safe and responsible access to waste. If said owner/occupier refuses in any way to adhere, the Municipality may suspend the service until the owner/occupier indemnifies the Municipality in writing in respect of any damage or injury or other claims arising of either before resuming the service.</p>
			 
			 <p><strong>Waste types that we collect</strong><br>
			    <strong>Waste disposal:</strong> Where the Municipality notices the absence of an approved container and no request for replacement has been received, it may provide an approved container and recover the cost from the owner/occupier. In case of damage caused through the negligence of the owner/occupier of the premises, the container may be replaced by the Municipality after receiving a written request for such replacement and full payment of the cost involved. The owner/occupier of a residential or business premise shall be responsible for marking the container/s with the stand number to ensure easy identification thereof and to assist the municipal employees to return it to the correct stand. On your scheduled removal day your approved container must be placed outside the entrance of your premises before 07h00 and taken back inside before sunset on the same day.</p>
			 
			 <p style ="text-align:justify;"><strong>IN TERMS OF THE PROMOTION OF ACCESS TO INFORMATION ACT YOU HAVE THE RIGHT TO REQUEST INFORMATION FROM THE MUNICIPALITY IF NOT OTHERWISE MADE AVAILABLE TO YOU</strong></p>
			 
			 <p style ="text-align:justify;">Waterval Landfill is the Municipality’s permitted waste disposal facility which receives general waste (including domestic, business, garden and building waste) and industrial waste which results inter alia from manufacturing, processing and maintenance activities. No hazardous waste of any quantity may be disposed of at the site. Strict conduct rules apply at the Waterval Landfill and persons entering the site do so at their own risk. Different tariffs for the disposal of different waste types and volumes are payable but residents are allowed free disposal of a certain volume of general waste. The Municipality may prescribe the maximum size of vehicle allowed to enter the landfill site. Farm owners or occupiers are encouraged to also make use of the landfill facility through the Municipality’s coupon system.</p>
			 
			 <p style ="text-align:justify;">The Municipality can assist with the removal of garden waste and bulky waste by special request and at a prescribed fee. Assistance with bulky waste will depend if the Municipality has suitable equipment available. Otherwise the consumer must use a licensed service provider and remove the waste within 14 days of generation thereof to a disposal facility / site as directed. Accumulation of waste is an offence and will be fined. Building waste and the anticipated handling and volumes thereof must be included in building plans submitted for new buildings / alterations to existing buildings. This waste must be kept on the building/alteration site and must not become unsightly. Upon written request, bulk containers placed on a verge for a specified duration may be approved by the Municipality . All building waste must be removed and disposed of continuously so as to prevent unnecessary accumulation thereof. The Municipality will determine the waste handling / disposal facility where said building waste must be disposed of. Generators of special industrial, health care and hazardous waste need to analyse, report, store, handle, collect, transport and dispose of it according to very strict specifications to ensure compliance with health and safety regulations, national standards and the Municipality’s by-laws. Businesses / industries generating such waste may only procure service providers that are licensed with the Municipality to collect, transport and dispose of such waste. The Municipality will determine to which waste disposal facility such waste may be taken. FURTHER CONSULT THE BY-LAW.</p>
				
			 <p style ="text-align:justify;">Industrial waste, special waste including e-waste must be stored in accordance with applicable legislation, national standards and SANS Codes in approved containers not kept in public places. Only a licensed service provider may collect said waste and transport and dispose of it at a waste disposal facility as designated by the Municipality and specific times can also be determined for acceptance of special waste at this site. A farm owner or occupier may dispose general household waste which may include agricultural and farm waste, on-site but if such waste exceeds the legislatively allowed quantity for on-site disposal or contains any quantity of hazardous waste, he/she must obtain the prescribed waste management license. The Municipality may request proof of such a license. Tyres, disused vehicles/machinery, scrap metal and WEEE (i.e. electronic and electrical equipment waste) may not be stockpiled / stored unless this activity is managed in accordance with national standards or licensed i.t.o. national legislation. These objects / items are not accepted at any of the Municipality’s waste handling/disposal sites. Any person disposing of these materials must do so at the premises of a legally compliant special industry body/local waste processor/buy-back centre or recycler as directed by the Municipality. The Municipality may access premises used for such storage / stockpiling and request proof of its integrated waste management plan, licenses or other applicable documents to verify compliance with legislation. Household and business hazardous waste may be temporarily stored in very small quantities in a manner not creating a nuisance / causing harm to human health or the environment. Material stored must be either collected by an authorized service provider or dropped off at a waste handling / disposal facility designated by the Municipality and i.t.o. conditions determined for such waste handling / disposal thereof; or at a legally compliant special industry body / waste processor / buy-back centre or recycler as directed by the Municipality.</p>
			 
			 <p style ="text-align:justify;"><strong>What about other waste types that we do not collect:</strong> Clearly mark your waste bin with your stand number and place it before 07h00 on your scheduled removal day outside the entrance of your premises or in a location indicated by the Municipality or in such a place that it does not obscure road visibility for motorists and take it back inside before sunset on the same day. Make sure that your waste bin is clean, in a good condition, kept closed, does not contain waste that can injure the waste removal crew or complicate removal, e.g. unwrapped glass or liquid or bulky waste and do not place hot ash in your waste bin. Make sure that your waste bin does not contain any hazardous waste such as fluorescent lights, batteries, drain cleaners, oil paint, motor oil, pesticides, poisons or e-waste with hazardous components. Hotels, restaurants, etc. ensure that the daily putrescible waste (organic matter) is not placed in a container where it contaminates other types of waste. Make sure that the premises for the storage of containers is not visible from a public road or public place and permits convenient access to and egress for the municipal waste collection vehicle. Keep the pavement in front of or abutting your premises clean and free of refuse. Do not accumulate waste and cause a nuisance for other residents and if you make compost of your garden waste make sure it causes no bad odours or other environmental or health hazards. Minimise the waste you generate and recycle all your plastics, paper, glass and metals by putting them in separate bags and drop these off at the waste facility the Municipality provides at the Waterval Landfill Site or the drop-off centres for recyclables when so established. Pay your municipal bill, notify us immediately of any change of address and/or ownership of the property for billing purposes and promptly report service difficulties or faults. Fully co-operate with an identified authorized official of the Municipality in any inspection such an official may deem necessary especially if an emergency situation which can cause harm to human health or damage to the environment arises.</p>

			 
			 <p style ="text-align:justify;"><strong>YOUR RESPONSIBILITIES:</strong> Power of entry and inspection: On request you must allow an authorised official of the Municipality access to your premises to carry out an inspection / examination that relates to any contravention of the Integrated Waste Management By-law and to ensure compliance therewith. It is an offence to obstruct or hinder an authorised official in the carrying out of his/her duties whether by refusing access to the premises or the failure to provide information or the furnishing of false information. The authorised official must, if requested, identify him/herself by means of an appointment certificate. The Municipality will give a consumer notice if an authorised official needs to gain entry to your property to do an inspection or examination unless it is an emergency such as suspected environmental pollution. Force may not be used to affect entry to execute work or conduct an inspection on your premises unless an emergency arises.</p>
			 
			 <p style ="text-align:justify;">Littering and dumping is not allowed – perpetrators will be prosecuted No person may drop, throw, deposit, spill, dump or discard in any other way litter or waste in a public place or road, a municipal drain, land, a vacant erf or stream. The Municipality will take reasonable steps to provide sufficient containers in towns and other public places for littering not to take place. No person may use a container provided for litter to dispose of domestic / business / garden waste or disturb / remove litter from such a container in a way that litter is spilled. No owner or occupier of land may use his land or allowed it to be used for unlawful dumping of waste. Protect your land because, if the Municipality must remove litter or waste from your land or premises, the person having control of the land will be held liable for the removal costs and rehabilitation of the environment.</p>
			 
			 <p style ="text-align:justify;">The Waterval Landfill is located at <strong>“S25’40’26.28” “E27’16’57.78”</strong> and is open: Monday—Saturday 07h00 to 18h00 & Sunday and Public Holidays 08h00 to 17h00 (except Christmas Day)</p>
			 
			 <p style ="text-align:justify;"><strong>THE BURNING OF WASTE IS STRICTLY PROHIBITED UNLESS AUTHORISED BY THE CHIEF FIRE OFFICER IN TERMS OF THE FIRE SAFETY BY-LAW OF THE RUSTENBURG MUNICIPALITY</strong></p>
			 
			 <p style ="text-align:justify;"><strong>LICENSED SERVICE PROVIDERS FOR COMMERCIAL SERVICES:</strong> No person may provide commercial services for the collection and transport of waste in the municipal area unless he/she has registered with the Municipality and obtained a license authorising these waste management activities. To obtain such a license a service provider must submit a written application which the Municipality will consider within 30 days of its receipt subject to the criteria as mentioned in the Municipality’s Integrated Waste Management By-law. A license must be annually renewed.</p>
			 
			 <p style ="text-align:justify;"><strong>Exemptions:</strong> Any person may in writing with full reasons apply to the Municipality for exemption from any provision of the Integrated Waste Management By-law. The Municipality may grant an exemption with conditions and for a period as determined or refuse it with reasons. If an exemption is granted, the applicant must undertake to comply with the conditions as imposed otherwise the Municipality may revoke the exemption after due notice to the person concerned.</p>
			 
			 <p style ="text-align:justify;">A person conveying waste upon a public road must do so in a clean, sanitary and roadworthy vehicle suitable for the type of waste transported. An open vehicle transporting loose waste through the municipal area must be covered with a tarpaulin or net to ensure no waste become detached, leak or fall from the vehicle.</p>
			 
			 <p style ="text-align:justify;"><strong>Transportation of Waste:</strong> Obtain the Integrated Waste Management By-law & Fine Schedule from our website: www.rustenburg.gov.za Fines applicable to this By-law: In accordance with Section 57(5) of Act 51 of 1977, the Fine Schedule for the Integrated Waste Management By-law has been approved by the Chief Magistrate for the urban and rural areas of the Rustenburg Magisterial District as from 13 July 2016. This means that persons guilty of an offense i.t.o. the By-law can be fined the applicable amount approved by the Chief Magistrate. Fines range from R500 for e.g. overturned waste containers, waste spillage, containers placed outside on days other than collection days for an area and containers containing hazardous waste to R3500 for littering public places or allowing premises to be used for unlawful dumping of waste. Other fines are inter alia R1800 for unauthorized use of a bulk container for building waste; R1500 for accumulation of waste on premises; R1500 for failing to register with the Municipality as commercial service provider handing waste and R1000 for failing to comply with any notice issued i.t.o. the By-law.</p>
		
	</div>


<!-- footer Start -->
<?php include ('../includes/inc_footer.php')?>
<?php include ('../includes/inc_page_bottom.php')?>

</body></html>